---
# /etc/.setip_config_hash: the VPS provider's setip.sh (configuring networking for the VPS) stores a config hash to skip reruns
rkhunter_allowed_hidden_files:
  - /etc/.setip_config_hash
proxy_sub_domain: p.myl.moe
proxy_sub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_sub_key: /etc/nginx/tls/cloudflare/myl.moe.key
proxy_reality_fallback_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_reality_fallback_key: /etc/nginx/tls/cloudflare/myl.moe.key
vaultwarden_domain: key.myl.moe
vaultwarden_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
vaultwarden_key: /etc/nginx/tls/cloudflare/myl.moe.key
gitea_domain: git.myl.moe
gitea_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
gitea_key: /etc/nginx/tls/cloudflare/myl.moe.key
miniflux_domain: read.myl.moe
miniflux_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
miniflux_key: /etc/nginx/tls/cloudflare/myl.moe.key
rsshub_domain: rss.myl.moe
rsshub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
rsshub_key: /etc/nginx/tls/cloudflare/myl.moe.key
dav_domain: dav.myl.moe
dav_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
dav_key: /etc/nginx/tls/cloudflare/myl.moe.key
uptime_domain: uptime.myl.moe
uptime_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
uptime_key: /etc/nginx/tls/cloudflare/myl.moe.key
s3_domain: s3.myl.moe
s3_console_domain: s3-console.myl.moe
s3_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
s3_key: /etc/nginx/tls/cloudflare/myl.moe.key
s3_console_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
s3_console_key: /etc/nginx/tls/cloudflare/myl.moe.key
gost_domain: tun.myl.moe
gost_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
gost_key: /etc/nginx/tls/cloudflare/myl.moe.key
mc_auth_domain: mcauth.myl.moe
mc_auth_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
mc_auth_key: /etc/nginx/tls/cloudflare/myl.moe.key
prules_domain: prules.myl.moe
prules_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
prules_key: /etc/nginx/tls/cloudflare/myl.moe.key
shortlink_domain: my6.co
shortlink_cert: /etc/nginx/tls/cloudflare/my6.co.pem
shortlink_key: /etc/nginx/tls/cloudflare/my6.co.key
shortlink_links_repo: git@100.97.128.26:myl7/sl.git
osu_taste_domain: osu.myl.moe
osu_taste_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
osu_taste_key: /etc/nginx/tls/cloudflare/myl.moe.key
cliproxy_domain: ai.myl.moe
cliproxy_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
cliproxy_key: /etc/nginx/tls/cloudflare/myl.moe.key
cityu_print_domain: cityu-print.myl.moe
cityu_print_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
cityu_print_key: /etc/nginx/tls/cloudflare/myl.moe.key
cityu_print_socks_host: 100.69.54.3
cityu_print_socks_port: 10800
cityu_print_server: 144.214.36.203
cityu_print_queue: g7352
cityu_print_queues:
  - g7352
  - G7356
  - G7751
  - G7C
  - Y6407
  - Y7714
  - MMW2462
  - Inno_01
  - Inno_02
  - inno_03
  - Inno_04
  - Inno_05
cityu_print_job_user: cityu-print.myl.moe
cityu_print_job_origin: cityu-print.myl.moe
