---
# /etc/.setip_config_hash: the VPS provider's setip.sh (configuring networking for the VPS) stores a config hash to skip reruns
rkhunter_allowed_hidden_files:
  - /etc/.setip_config_hash
proxy_sub_domain: p.myl.moe
proxy_sub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_sub_key: /etc/nginx/tls/cloudflare/myl.moe.key
vaultwarden_domain: key.myl.moe
vaultwarden_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
vaultwarden_key: /etc/nginx/tls/cloudflare/myl.moe.key
gitea_domain: git.myl.moe
gitea_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
gitea_key: /etc/nginx/tls/cloudflare/myl.moe.key
miniflux_domain: read.myl.moe
miniflux_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
miniflux_key: /etc/nginx/tls/cloudflare/myl.moe.key
rsshub_domain: rss.myl.moe
rsshub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
rsshub_key: /etc/nginx/tls/cloudflare/myl.moe.key
dav_domain: dav.myl.moe
dav_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
dav_key: /etc/nginx/tls/cloudflare/myl.moe.key
uptime_domain: uptime.myl.moe
uptime_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
uptime_key: /etc/nginx/tls/cloudflare/myl.moe.key
s3_domain: s3.myl.moe
s3_console_domain: s3-console.myl.moe
s3_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
s3_key: /etc/nginx/tls/cloudflare/myl.moe.key
s3_console_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
s3_console_key: /etc/nginx/tls/cloudflare/myl.moe.key
