---
proxy_sub_domain: p.myl.moe
proxy_sub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_sub_key: /etc/nginx/tls/cloudflare/myl.moe.key
vaultwarden_domain: key.myl.moe
vaultwarden_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
vaultwarden_key: /etc/nginx/tls/cloudflare/myl.moe.key
gitea_domain: git.myl.moe
gitea_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
gitea_key: /etc/nginx/tls/cloudflare/myl.moe.key
miniflux_domain: read.myl.moe
miniflux_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
miniflux_key: /etc/nginx/tls/cloudflare/myl.moe.key
dav_domain: dav.myl.moe
dav_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
dav_key: /etc/nginx/tls/cloudflare/myl.moe.key
uptime_domain: uptime.myl.moe
uptime_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
uptime_key: /etc/nginx/tls/cloudflare/myl.moe.key
