---
proxy_sub_domain: p.myl.moe
proxy_sub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_sub_key: /etc/nginx/tls/cloudflare/myl.moe.key
proxy_reality_fallback_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
proxy_reality_fallback_key: /etc/nginx/tls/cloudflare/myl.moe.key
gitea_domain: git.myl.moe
gitea_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
gitea_key: /etc/nginx/tls/cloudflare/myl.moe.key
rsshub_domain: rss.myl.moe
rsshub_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
rsshub_key: /etc/nginx/tls/cloudflare/myl.moe.key
prules_domain: prules.myl.moe
prules_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
prules_key: /etc/nginx/tls/cloudflare/myl.moe.key
cliproxy_domain: ai.myl.moe
cliproxy_cert: /etc/nginx/tls/cloudflare/myl.moe.pem
cliproxy_key: /etc/nginx/tls/cloudflare/myl.moe.key
