[hosts.vars]
ansible_user = "{{ username }}"
ansible_port = 50000

[hosts.hosts]
sg = { ansible_host = "38.54.16.65" }
bwh = { ansible_host = "104.243.29.231" }

[web.hosts]
sg = {}

[proxy.hosts]
sg = {}
bwh = {}

[raw]
children = ["lightnode", "bandwagon"]

[raw.vars]
ansible_ssh_common_args = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

[lightnode.vars]
ansible_user = "root"
ansible_port = 22
ansible_ssh_private_key_file = "{{ inventory_dir }}/../playbooks/secrets/ssh/id_rsa"

[lightnode.hosts]
"sg.raw" = { ansible_host = "38.54.16.65" }

[bandwagon.vars]
ansible_user = "root"
ansible_port = 50000

[bandwagon.hosts]
"bwh.raw" = { ansible_host = "104.243.29.231" }
